### ISSUE TITLE
installation instructions not working for me

### ISSUE THREAD

**Issue by aroopganguly** [lucidworks/zeppelin-solr#30]
Installation instructions are:
**./bin/install-interpreter.sh --name solr --artifact com.lucidworks.zeppelin:zeppelin-solr:0.1.5**

I keep getting these messages:

Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/aroopganguly/zeppelin-0.8.2-bin-all/lib/interpreter/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/aroopganguly/zeppelin-0.8.2-bin-all/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Install solr(com.lucidworks.zeppelin:zeppelin-solr:0.1.5) to /Users/aroopganguly/zeppelin-0.8.2-bin-all/interpreter/solr ... 
org.sonatype.aether.RepositoryException: Cannot fetch dependencies for com.lucidworks.zeppelin:zeppelin-solr:0.1.5
	at org.apache.zeppelin.dep.DependencyResolver.getArtifactsWithDep(DependencyResolver.java:179)
	at org.apache.zeppelin.dep.DependencyResolver.loadFromMvn(DependencyResolver.java:128)
	at org.apache.zeppelin.dep.DependencyResolver.load(DependencyResolver.java:76)
	at org.apache.zeppelin.dep.DependencyResolver.load(DependencyResolver.java:93)
	at org.apache.zeppelin.dep.DependencyResolver.load(DependencyResolver.java:85)
	at org.apache.zeppelin.interpreter.install.InstallInterpreter.install(InstallInterpreter.java:170)
	at org.apache.zeppelin.interpreter.install.InstallInterpreter.install(InstallInterpreter.java:148)
	at org.apache.zeppelin.interpreter.install.InstallInterpreter.main(InstallInterpreter.java:276)
Caused by: java.lang.NullPointerException
	at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:352)
	at org.apache.zeppelin.dep.DependencyResolver.getArtifactsWithDep(DependencyResolver.java:176)
	... 7 more

**Comment by manlioGit** [comment]
try with

```
ZEPPELIN_INTERPRETER_DEP_MVNREPO=https://repo1.maven.org/maven2 bin/install-interpreter.sh --name solr --artifact com.lucidworks.zeppelin:zeppelin-solr:0.1.6
```

or with docker:

```
docker run --rm -e ZEPPELIN_INTERPRETER_DEP_MVNREPO=https://repo1.maven.org/maven2 --name zeppelin -d apache/zeppelin:0.8.2
docker exec zeppelin ./bin/install-interpreter.sh --name solr --artifact com.lucidworks.zeppelin:zeppelin-solr:0.1.6
```

**Comment by epugh** [comment]
Is this a closable issue?   We are up to 0.1.6, and I suspect a new version will be cut soon!

**Comment by storesund** [comment]
*Didn't see a better place to post this:*
Just in case someone else is struggling with the installation on Zeppelin v0.10.0 or similar **running in Docker/Container**:
The permissions set on the interpreter folder has changed, meaning that you might get a "cannot create folder" error when trying to install the zeppelin-solr interpreter..

I'm sure there are nice and clean ways to correct this, one of them being to install the interpreter in a modified docker build. But the quick solution (that works for me) is to run something like the following:

```bash
# Set the MVN repo, and also set the port mapping to be sure:
docker run --rm -e ZEPPELIN_INTERPRETER_DEP_MVNREPO=https://repo1.maven.org/maven2 --name zeppelin10 -d -p 8080:8080 apache/zeppelin:0.10.0
# Add "-u 0" to force the command being run as root, allowing the installation:
docker exec -u 0 zeppelin10 ./bin/install-interpreter.sh --name solr --artifact com.lucidworks.zeppelin:zeppelin-solr:0.1.6
# Restart Zeppelin:
docker restart zeppelin10
```
PS: This works for me, and the connection to Solr running in another docker container works fine (but pay attention to docker networking if you do this - "localhost" is not accessible by default and you will have to modify the interpreter baseUrl)
PPS: Contrary to Zeppelin 0.8.x, if I create a notebook with Solr as the default interpreter I cannot write %solr at the top of the cell (the interpreter complains that I didn't use a valid command). Everything works if I write the main command (search, facet) on the first line..
