### ISSUE TITLE
OOM error while running streaming expression

### ISSUE THREAD

**Issue by aroopganguly** [lucidworks/zeppelin-solr#6]
Hi Team

I am running a streaming expression to do a simple count, and Zeppelin keeps giving me an OOM error, mentioned below. Any thoughts how to proceed? 
```
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at scala.collection.mutable.StringBuilder.$plus$plus$eq(StringBuilder.scala:177)
	at com.lucidworks.zeppelin.solr.SolrQuerySupport$$anonfun$doStreamingQuery$2.apply(SolrQuerySupport.scala:363)
	at com.lucidworks.zeppelin.solr.SolrQuerySupport$$anonfun$doStreamingQuery$2.apply(SolrQuerySupport.scala:359)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at com.lucidworks.zeppelin.solr.SolrQuerySupport$.doStreamingQuery(SolrQuerySupport.scala:359)
	at com.lucidworks.zeppelin.solr.SolrQuerySupport.doStreamingQuery(SolrQuerySupport.scala)
	at com.lucidworks.zeppelin.solr.SolrInterpreter.interpret(SolrInterpreter.java:108)
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.interpret(LazyOpenInterpreter.java:97)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:498)
	at org.apache.zeppelin.scheduler.Job.run(Job.java:175)
	at org.apache.zeppelin.scheduler.FIFOScheduler$1.run(FIFOScheduler.java:139)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by kiranchitturi** [comment]
Were you trying to import a lot of rows? Increasing Zeppelin heap memory will help here

**Comment by aroopganguly** [comment]
possibly. I will review and get back to this thread. thanks for your input.

**Comment by kiranchitturi** [comment]
I am going to close this one out. Please open a new issue if you think it's a problem with zeppelin-solr
