### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by aroopganguly** [lucidworks/zeppelin-solr#9]
we keep getting this issue when installing zeppelin solr from scratch.
this happens after following the steps mentioned on the readme, and then trying to create a notebook and running the "list" command

`org.apache.thrift.TApplicationException: Internal error processing createInterpreter
	at org.apache.thrift.TApplicationException.read(TApplicationException.java:111)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:71)
	at org.apache.zeppelin.interpreter.thrift.RemoteInterpreterService$Client.recv_createInterpreter(RemoteInterpreterService.java:209)
	at org.apache.zeppelin.interpreter.thrift.RemoteInterpreterService$Client.createInterpreter(RemoteInterpreterService.java:192)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreter$2.call(RemoteInterpreter.java:169)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreter$2.call(RemoteInterpreter.java:165)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterProcess.callRemoteFunction(RemoteInterpreterProcess.java:135)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreter.internal_create(RemoteInterpreter.java:165)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreter.open(RemoteInterpreter.java:132)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreter.getFormType(RemoteInterpreter.java:299)
	at org.apache.zeppelin.notebook.Paragraph.jobRun(Paragraph.java:407)
	at org.apache.zeppelin.scheduler.Job.run(Job.java:188)
	at org.apache.zeppelin.scheduler.RemoteScheduler$JobRunner.run(RemoteScheduler.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)`

**Comment by aroopganguly** [comment]
On further investigation I see this exception in the interpreter log:
`Caused by: java.lang.ClassNotFoundException: com.lucidworks.zeppelin.solr.SolrInterpreter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer.createInterpreter(RemoteInterpreterServer.java:301)
`

**Comment by aroopganguly** [comment]
can any anyone help me in understanding what am I doing wrong here ?

**Comment by aroopganguly** [comment]
@kiranchitturi would you please advise ?

**Comment by aroopganguly** [comment]
I was able to get around this issue by adding com.lucidworks.zeppelin:zeppelin-solr:0.0.1-beta as an artifact while creating the interpreter.

**Comment by aroopganguly** [comment]
it would be good though to understand why it does not work as advertised on the readme though.

**Comment by kiranchitturi** [comment]
Hi @aroopganguly. Apologies for being inactive for a while.

I have looked into this installation issue and replicated with 0.8.0 version. The command works fine with 0.7.x. Looks like the problem is with the interpreter name, the command I had in README used `zeppelin-solr` instead of `solr` and that caused 0.8.0 to fail for some reason. I will fix the README

```
 ./bin/install-interpreter.sh --name solr --artifact com.lucidworks.zeppelin:zeppelin-solr:0.0.1-beta2
```
